export * from './LoginPage/LoginPage.jsx';
export * from './RegisterPage/RegisterPage.jsx';
export * from './DashboardPage/DashboardPage.jsx';
export * from './OrdersPage/OrdersPage.jsx';
export * from './CartsPage/CartsPage.jsx';
export * from './catalogSectionPages/ProductPage/ProductPage.jsx';
export * from './catalogSectionPages/CategoriesPage/CategoriesPage.jsx'
export * from './catalogSectionPages/BrandsPage/BrandsPage.jsx';
export * from './ClientsPage/ClientsPage.jsx';
export * from './ReviewsPage/ReviewsPage.jsx';
export * from './DiscountsPage/DiscountsPage.jsx';
export * from './StocksPage/StocksPage.jsx';
export * from './ShippingPage/ShippingPage.jsx';
export * from './PaymentsPage/PaymentsPage.jsx';
export * from './ReturnsPage/ReturnsPage.jsx';
export * from './SettingsPage/SettingsPage.jsx';
export * from './VerifyEmailPage/VerifyEmailPage.jsx';